### PR TITLE
Updates Podfile for ResultType.

### PR DESCRIPTION
**Pull request by ashfurrow**

### CODE REVIEW

**Comment by ashfurrow** [comment]
I see the ResultType was added in https://github.com/JensRavens/Interstellar/commit/fd58e53a049a29f5036e2d420255c0af81dac8b7 but not the `Observable+Result.swift` file. I've pulled latest from your repo here, if you'd like to merge (or whatever works for you, maybe this file doesn't belong in the Core subspec?).

**Comment by JensRavens** [comment]
Yep, I've just missed yet another file :)

**Comment by mergesort** [comment]
This might be a bit late, but what do y'all think about instead of having all the source files at one level, creating a folder for `Core`, and `WarpDrive` for the subspec.

Then instead of manually writing the files like so (in a potentially error prone fashion):

```
 cs.source_files = ["Sources/Result.swift", "Sources/Signal.swift", "Sources/Observable.swift", "Sources/Mutex.swift", "Sources/ResultType.swift", "Sources/Observable+Result.swift"]
```

You'd be able to simplify it to these respectively:

```
 cs.source_files = ''*/Core/*.swift'
 cs.source_files = ''*/WarpDrive/*.swift'
```

Happy to submit a PR for it if that sounds reasonable.

**Comment by ashfurrow** [comment]
Yeah, that makes sense. We've done something similar on Moya.

**Comment by JensRavens** [comment]
@mergesort Sounds like a good idea. Do we have to add some swift file on the root level to make the SPM happy? (on SPM this should still be one module so you don't constantly have to import Core and WarpDrive separately).

**Pull request merged**
