### PR TITLE
Added subscribeNext method 

### PR DESCRIPTION
**Pull request by BenchR267**
This method should be used if someone wants to subscribe to this signal without getting notified about the current value.

### CODE REVIEW

**Comment by BenchR267** [comment]
@JensRavens is there a reason this has not been merged yet?

**Comment by JensRavens** [comment]
Hey Benjamin,
I just returned from a vacation tonight. That's why I haven't responded yet.

I'm a bit concerned `subscribeNext` is named a bit to close to `next` which is doing a completely different thing. We've been discussing about renaming `next` to `then` in the future, inspired by javascripts promises.

In the [v2 branch](https://github.com/JensRavens/Interstellar/blob/feature/v2/Sources/Observable.swift) I experimented with making this a property of the signal. Although this seems to be a subscribing thing, most signals can be grouped in "saves the last state" (text fields) and "is event based" (buttons) (see issue #13). If we make this a subscribing option, it should also be available in the `next` and `error` method. I'm not sure how to handle this, but I think it needs further discussion.

**Comment by BenchR267** [comment]
Hey Jens,
thanks for the answer, hope your vacation was awesome :)

The naming is based on the naming that is used in ReactiveCocoa. You are right, it might be too near to the naming of 'next'. Making this part of the next/then-method with an optional subscribe-option would be even more awesome, totally agree! Something I can help with?

And btw: awesome work with that framework, really enjoying using it! Looking forward to join swift.berlin in some of the next months :)

Greetings from Dresden ;)

**Comment by JensRavens** [comment]
I think it's ok to rename `next` to `then` (maybe even renaming `error` to `catch` to stay consistent with [javascript promises](http://www.html5rocks.com/en/tutorials/es6/promises/)).

Should we make `supply initial value` an option of the subscriber or of the signal?
A button signal already knows it should not supply it's initial value (+1 for signal), a textfield might want to supply it's initial value for form validation (+1 for signal) or the subscriber just wants to get notified about typing (+1 for subscriber).

In terms of flexibility options on subscribe seem to be easier, but also more verbose. Also: What is the default value?

**Comment by BenchR267** [comment]
I think offering the supply initial value option would be awesome. I am just thinking about more options that might help so that something like a configuration object would make sense. But maybe that would be too overkill. 
The default value should be false since otherwise it might break existent implementations.

**Comment by JensRavens** [comment]
The implementation of `Observable<T>` (see [here](https://github.com/JensRavens/Interstellar/blob/feature/v2/Sources/Observable.swift)) is using an OptionSetType as a configuration object (successor of `NSEnum`) on the observable instead of the subscription. Unsubscribing is done via a special `ObserverType`-protocol (which is currently a class, but should be a protocol as soon as I have figured out how). Do you think this is a valid way?

**Comment by BenchR267** [comment]
Ah, that is a great solution actually!

**Pull request closed without merging**
