### PR TITLE
Moves public unsubscription to observer token.

### LINKED ISSUE #40: More complex unsubscription in v2
The current subscription/unsubscription mechanism in v2 relies on having both the `Observable` and the `ObserverToken`, which complicates things slightly. For use in a table view cell, for example, we need to unsubscribe during `prepareForReuse()`, and afterward set the observable and the token to be `nil`. This requires some awkwardness, either with:

``` swift
if let observerToken = observerToken, observable = observable {
    observable.unsubscribe(observerToken)
}
self.observerToken = nil
self.observable = nil
```

Or something with tuples:

``` swift
var subscription: (ObserverToken, Observable<Whatever>)?

...

if let subscription = subscription {
    subscription.1.unsubscrive(subscription.0)
}
subscription = nil
```

Neither is particularly awesome. I'd like to consider using a more complex `ObserverToken` that has a weak or unowned reference to the observable it's bound to, so we don't need to hang on to both observable and observer token. Any thoughts? Happy to send a PR if you like the idea.

### PR DESCRIPTION
**Pull request by ashfurrow**
This is a first-pass, happy to amend based on any feedback. Changed the existing tests to support the new behaviour. If this looks good to you, I'll update the documentation, too.

Fixes #40.

### CODE REVIEW

**Comment by orta** [comment]
This looks like what I'd expect 👍

**Comment by JensRavens** [comment]
Looks good to me! 

Just a minor remark: I would like keep the `[:]` syntax for dictionaries.

**Comment by ashfurrow** [comment]
Thanks! Got a compiler error with `[ObserverToken<T>: Oberserver]` and switched to fix it. I'll take another look and see if I can figure it out.

**Comment by ashfurrow** [comment]
I was able to restore the original dictionary syntax using a private typealias; I've amended my commit to keep the history clean.

**Comment by JensRavens** [comment]
Thanks for waiting so long. I definitely need more time for this project :)

**Comment by ashfurrow** [comment]
Don't worry about it – life comes first! I've watched the repo and will try to provide feedback on issues and PRs. Let me know if there's any other way I can help.

**Pull request merged**
