### PR TITLE
Upgrade to Xcode 9.3 and Swift 4.1

### PR DESCRIPTION
**Pull request by loudmouth**
^=~~Drops support for Swift 3.2/3.3~~

Additionally updates the `Package.swift` manifest to version 4.0 of `swift-tools`

Hey @JensRavens 

What do you think about making this change now?

If you're amenable, could we publish a new version? I imagine it may need to be a 3.0.0 as it will break backwards compatibility with Xcode 8.

### CODE REVIEW

**Comment by loudmouth** [comment]
...not quite sure why the build fails—looks like running:
```
xcodebuild build -project Interstellar.xcodeproj -scheme Interstellar_watchOS -sdk watchsimulator ONLY_ACTIVE_ARCH=NO -configuration Release
```
i.e. just building (not testing) the watch target, is also trying to compile `DebounceTests.swift` and this is causing a failure. 🤔

**Comment by loudmouth** [comment]
Not sure why the `swift test` command fails on travis. It succeeds on my machine...

**Comment by andrewcampoli** [comment]
@loudmouth It's failing on the watchOS target for the `Release` build configuration. It's unable to import `Interstellar`. I think enabling `Testability` for that configuration and target might fix the Travis build. You can change the `Testability` flag in `Build Settings`.

**Comment by loudmouth** [comment]
Thanks @andrewcampoli ...looking into it now.

**Comment by loudmouth** [comment]
Hey @andrewcampoli although at a quick glance the failure output looked like it may have been from the watchOS build command, the failure was indeed from `swift test`...i should have thought to check the `.swift-version` file when i first submitted the PR: 🤦‍♂️ 

This also helped me realize that the `Package.swift` file should have also been updated to `swift-tools` 4.0

The build is passing now. 

@JensRavens any chance we can get a review and release? Would love to clean up the build warnings in my project 🙂

**Comment by JensRavens** [comment]
Thank you very much for all your work, I'm really happy someone is taking care of this!

What do you think about versioning this release? By switching to Swift 4 we're breaking backwards compatibility, so it should be 3.0, right?

**Comment by loudmouth** [comment]
Hey @JensRavens I just tested using my branch in a test project and used a post install script in cocoapods to force the `SWIFT_VERSION` to 3.3 (the bridge for Swift 3.2 and Swift 4.x).  for the pod dependencies. I added an `import Interstellar` and initialized an Observable. The project built and ran!

The test project had it's own `SWIFT_VERSION` set to 3.3 in Xcode build settings for its own target and everything worked. Even without my post install script to set the `SWIFT_VERSION` on Interstellar, the project still compiled and ran.

Anyway, the TL;DR is that it looks like this PR does ensure backwards compatibility still 🎉 and I've edited the PR description above to reflect that change. maybe we could use version `2.2.0`?

WDYT?

**Comment by JensRavens** [comment]
Oh, that's perfect! Can you add an entry to the changelog in the readme? Then I can release it right away :)

**Comment by loudmouth** [comment]
Done!

**Review by JensRavens — APPROVED** [review]

**Comment by loudmouth** [comment]
thanks @JensRavens !

**Comment by JensRavens** [comment]
Ok, newest version is pushed to trunk. Thanks for you work! 👍

**Pull request merged**
