### PR TITLE
Adds merge() to Observable

### PR DESCRIPTION
**Pull request by ashfurrow**
Input welcome on this. I'm only using it in one spot, so if you feel it doesn't belong in the library, I can just put it in my own project.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Any update on this?

**Comment by JensRavens** [comment]
I'm finally back from UIKonf, now having time to work on this again.

I'm a bit concerned how this will work for signals that do not save their last value with `NoInitialValue` (spoiler: it doesn't). Is it enough to just mention that in the documentation? Or should we prevent this somehow?

**Comment by ashfurrow** [comment]
Hey no problem! I haven't used that option before, could you explain the consequences?

**Comment by JensRavens** [comment]
With `NoInitialValue` the last value of an observable is not cached (this is mainly needed when the process of subscribing is not meant to trigger an immediate update with the last known value, e.g. a button supplying a void-value).
This also helps reducing memory consumption / memory leaks in certain setups (because the observable is not keeping a reference to the value, it just notifies the subscriber).

**Comment by ashfurrow** [comment]
Hmm, I think I understand. So the result of calling `merge` doesn't maintain the contract with the `Observable`s initializers, essentially? Hmm, that is difficult. I'm not sure how we could reconcile the behaviour differences between the two. Suggestions?

**Comment by JensRavens** [comment]
`NoInitialValue` is pretty much my desperate try to unify Signals, Promises and Observables. Maybe it's just not a good idea and there should be two different classes instead (e.g. `Signal<T>` that has no state and `Observable<T>` that contains state.

**Comment by ashfurrow** [comment]
Ah interesting. Hmm, yeah that's pretty tricky. To be honest, I've not used it but only because I didn't immediately understand its purpose or function.

**Pull request merged**
